language: php
services:
- mysql
- elasticsearch
php:
- 7.0
- 7.1
before_script:
- mysql -uroot -e 'CREATE DATABASE colligator_test;'
- printf "\n" | pecl install imagick
- php -m
- cp .env.example .env
- composer install -o -n
- php artisan key:generate
script:
- DB_USERNAME=root DB_PASSWORD= vendor/bin/phpunit
notifications:
  email: false
  slack:
    secure: Ua3AgAegP2lZoaTFUMeqQIFLXniACxCbpCpa5OnNMfvlwGdrumFGnnh/b9+aZNsmZVog3rcPocO2uXJOWNhZUlk+jy9eB75Gl1VjlmgBIX48gudP2DO5DJWhSLtV6hMWyDkZo79OMBTTJx+ALrYNutCkw7eabuCloJX6QDtRMgZ4gcogTZcaZZUpUK5fC4Jlo65/DSA4u7MlmMacluyhBdvkr6RSzLVDCJPZMSl6FwZUBDvTQJ/HMAbKuUCW1A73+1ACqXk8TZ0+moT2Bo7v8JuYfMQAmjKA/soDdXRns8m6SucEDTZ9ipUL96Rc/aJz5VsD7s2oNyijZy/jPkOEmq7Pr4KTdR5qlsU6L0FIYGyNFz7YmhsJmzoY6wTTFO9ieRTwwNSeITmnYvsKWSiqUptViWIE2b9gJykmtnJYfpMRM6b4fkMIv+zLRuIgtKIEHB3V5txpvige334BOrhanttW6wC4jyiKTgOENatrsXVTTueBxs1EUuH1HAPLtEeuCL1ar1R6g/TD7kFyyyiv6X2YfLs8m7hOSpQWWuk0sRbRg5yRxxFdDb8wAOa1thhxOx/ooQ3/DCXHYtwcRxUNakEeWmuGlQuj9Ebm4DdfVZdVQkjlxQQgbbRjFSeVC+EVbyeab2sdEcNa1zfv7QDR2hhfotH68x3qkv34FYAHKr4=
